name: Task OS eng-nada-adel 

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: 'Testing Repository Actions'
        run: pwd

      # Another test step
      - name: 'Testing GitHub Actions'
        run: echo My GitHub Actions
